### ISSUE TITLE
Any possibility for this extension to support PHP 8?

### ISSUE THREAD

**Issue by elidrissidev** [RogerGee/php-git2#1]
Hey,

I came across this extension when looking for libgit2 bindings for PHP after I found that most of them are outdated and unmaintained. I would have loved to fix this extension for PHP 8 support and maybe even latest libgit2 support, but I have no idea how that works. Is there any plan to update this anytime in the future?

Thanks for your work.

**Comment by RogerGee** [comment]
It just so happens that I have recently been busy working on this extension! In fact, I just created a new maintenance release that overhauls the testing framework. (It needed a lot of work.) I still need to work on refactoring for `libgit2` version 1 and implementing for PHP 8. My goal is to try and have it support `libgit2` version 1 by end of year and then begin working on PHP 8 after that. Since this is a project I work on in my spare time, I cannot guarantee this timeline. I added a "Roadmap" section to the project README that indicates my plans for future work.

I started this project back in 2016 when I needed `libgit2` support in PHP and there was nothing good out there. At that time, `libgit2` was unstable, and so I stuck with an old version (and it has been stuck there ever since unfortunately). My top priority now is to get it working with version 1. I really would like this project to be the "go to" extension for `libgit2` support in PHP.

I'm optimistic that upgrading to version 1 won't be that difficult. I will focus at first on just refactoring the existing bindings instead of implementing any new ones. I'm also optimistic that the update for PHP 8 won't be too bad, but frankly I haven't had enough time to look into PHP 8 internals yet.

If you can get by using PHP 7 and `libgit2` v0.25.1 in the meantime, know that the extension is quite stable itself and covers about 85% of the bindings.

**Comment by elidrissidev** [comment]
@RogerGee That is exciting to hear! I already got it working with PHP 7.4 a few days ago but that meant I had to use an old version of my backend framework (Laravel 8.x) that still supports PHP 7. So it will certainly be great to have PHP 8 support at the very least.

I will also need stubs for the PHP API, preferably ones that support PhpStorm, which I will be creating based on [DOCS.txt](https://github.com/RogerGee/php-git2/blob/master/docs/DOCS.txt). Will you accept a PR to include them directly in this repo?

**Comment by RogerGee** [comment]
@elidrissidev I would definitely welcome any contributions that help document the project. The `DOCS.txt` file was just a quick way to keep notes about what I was doing; however, it is obviously not a very suitable documentation solution.

Regarding stubs specifically, it sounds like a great idea to add to the project. I've noticed that the PHP 8 codebase now includes stubs for builtin extensions (e.g. [ext/standard/basic_functions.stub.php](https://github.com/php/php-src/blob/e00dadf43a17da3bb79aba360d07e29b359c12b3/ext/standard/basic_functions.stub.php)). I'm not sure if this is the same format used by PhpStorm. I'd be fine with any number of formats as you see fit.

I think it would be best to store stubs in a subtree such as `docs/stubs`. Would this work?

One of the other things I would like to do with this project is create [official PHP documentation](https://github.com/php/doc-base) that can be generated into a website like https://www.php.net/docs.php. It would go under `docs/phpdoc` and could be generated into a static site using the official documentation tooling. I'd probably look into doing this myself after I get the other big items complete (i.e. `libgit2` v1 and PHP 8), but feel free to look into it if it interests you.

**Comment by elidrissidev** [comment]
> I've noticed that the PHP 8 codebase now includes stubs for builtin extensions (e.g. [ext/standard/basic_functions.stub.php](https://github.com/php/php-src/blob/e00dadf43a17da3bb79aba360d07e29b359c12b3/ext/standard/basic_functions.stub.php)). I'm not sure if this is the same format used by PhpStorm. I'd be fine with any number of formats as you see fit.

They seem very basic. [PhpStorm stubs](https://github.com/JetBrains/phpstorm-stubs) make use of some custom PHP Attributes available under the `JetBrains\PhpStorm` namespace to enhance the autocompletion and refactoring capabilities. I will be sure to submit a PR once I have it ready.

**Comment by RogerGee** [comment]
Quick update on this: I've updated the codebase to work with `libgit2` version 1. (I'm currently testing against version `1.5.0`, though earlier versions should probably work too.) I've pushed my development branch in case you want to try it out: [php7/develop](https://github.com/RogerGee/php-git2/tree/php7/develop).

The update was very easy; turns out not very much changed in terms of what I had already implemented. I have a few more things to work on before I'm happy enough to release the next version of the extension. After that I should be able to move on to looking at PHP 8 support.

The next release will be version 2.0.0 since `libgit2` version 1 did make a few backward-incompatible API changes against 0.25.1.

**Comment by elidrissidev** [comment]
Thanks!

**Comment by RogerGee** [comment]
I recently released a new version that targets `libgit2` version 1. I've also begun work on PHP 8 support. I will update here when I have something ready. Thanks for your patience!

**Comment by RogerGee** [comment]
I've implemented initial PHP 8 support for the extension. Please see the [`php8/devel` branch](https://github.com/RogerGee/php-git2/tree/php8/devel).

Support for PHP 8 is still experimental. You will notice a bunch of warnings when PHP first starts up like so:

~~~
Warning: Missing arginfo for GitRefDBBackend_Internal::compress() in Unknown on line 0

Warning: Missing arginfo for GitRefDBBackend_Internal::has_log() in Unknown on line 0

Warning: Missing arginfo for GitRefDBBackend_Internal::ensure_log() in Unknown on line 0

Warning: Missing arginfo for GitRefDBBackend_Internal::reflog_read() in Unknown on line 0
~~~

These are due to missing argument information. I will eventually have to provide argument information for each function and class method in the extension.

I will follow up in this thread when I'm closer to an official, tested PHP 8 release.

**Comment by elidrissidev** [comment]
Great work! Thanks a ton!

**Comment by xKZL** [comment]
Hi @RogerGee, thank you so much for this great work :)
I havent tested yet, but except the warning it is stable for production ?

**Comment by RogerGee** [comment]
@xKZL I can't really tell if all of the tests pass due to a few outstanding issues with getting the testbed to run. I will try to work on this some and get back to you. I haven't had a lot of time to devote to the project in recent months (and probably won't for the foreseeable future).

My guess is that it is fairly stable for production use. The update from PHP 7 to PHP 8 (and `git2` 0 to 1) was very minimal and shouldn't have affected the existing stability too much.

I went ahead and pushed up a few more commits that I hadn't published yet that add argument information for the classes. I still need to add stubs for the functions, which should take care of the remaining warnings.

**Comment by xKZL** [comment]
Hi @RogerGee thanks for your quick feedback !

I have prepare a PR trying to fix some deprecations in PHP8.2. (the version I am using right now)
This is not passing tests, because there is an issue I couldn't fix all of them by myself. (There is a remaining one due to <ReturnCode>).. but maybe this is not too much work to fix if I could get an hint
https://github.com/RogerGee/php-git2/pull/2

I might be intensively using php-git2, if I can get it work. So if there is a way I can help either in maintaining or testing some stuff, please let me know. I would be happy to contribute.

Cheers

**Comment by xKZL** [comment]
Hi @RogerGee,

I have installed the library but I am facing some issue I cannot fix by myself. Would you have any idea how to fix that ?
```
Warning: Missing arginfo for git2_version() in Unknown on line 0
Warning: Missing arginfo for git_libgit2_version() in Unknown on line 0
Warning: Missing arginfo for git_libgit2_prerelease() in Unknown on line 0
Warning: Missing arginfo for git_libgit2_features() in Unknown on line 0
[...]
Warning: Missing arginfo for git_worktree_validate() in Unknown on line 0
Warning: Missing arginfo for GitWritestream::write() in Unknown on line 0
Warning: Missing arginfo for GitWritestream::close() in Unknown on line 0
```

**Comment by xKZL** [comment]
@RogerGee do you have any idea about this issue I was facing? I couldn’t get it fix so far

**Comment by RogerGee** [comment]
@xKZL Those warnings are caused by missing argument information for the internal functions. It just needs to be added for the warnings to go away. PHP 8 requires that each internal function (and class method) provide argument information, whereas in previous versions of PHP it was optional.

I've added argument information for most of the class methods and am in the process of adding argument information for the functions. I will try to add placeholder arginfo soon in order to get the warnings to go away until we can actually (and laboriously) build out the stubs.

**Comment by xKZL** [comment]
Hi, I see ! I might try ti contribute in that regards then and fix some warning if I see some. Many thanks !

**Comment by RogerGee** [comment]
Okay, so I went ahead and added placeholder argument information for all function bindings. This will avoid the annoying warning messages.

I don't know what the implications of this are. I can get most of the testbed to pass for PHP 8.0 but there may be some issues with PHP 8.1. I have not tested with PHP 8.2 yet. I anticipate most of the issues going away once the real argument information is added.

As time permits, I will add argument information for the function bindings. Afterwards, I will resolve any outstanding issues with testbed errors. At that point, we should be close to an official PHP 8 release!

**Comment by RogerGee** [comment]
I finally have an official release ready for PHP 8! (It was very tedious getting the argument information added, but I eventually got it all done for the existing bindings.) I also figured out the issues with getting the unit tests to succeed. Turns out it wasn't due to anything in PHP 8, just a bug in the my test framework code!

This release is `php8/v2.0.0`. I have tested with 8.0 and 8.1. I will try to test with 8.2 when I get a chance to compile it. If anyone runs into any issues, I'm happy to take a look at them here on Github.
